spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
          filters:
            - name: AuthFilter

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**


        - id: auth-service
          uri: lb://auth-service
          predicates:
              - Path=/auth/**


        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transaction/**
          filters:
            - name: AuthFilter

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka


server:
  port: 8080



