server:
  port: 8083

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_account
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
